from __future__ import annotations

import hashlib
import os
import plistlib
import re
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from .config import GoalConfig, validate_config
from .runtime import RuntimeOptions, cleanup_runtime, run_goal


MANAGER_AUTO = "auto"
MANAGER_LAUNCHD = "launchd"
MANAGER_SYSTEMD_USER = "systemd-user"
SUPPORTED_MANAGERS = {MANAGER_AUTO, MANAGER_LAUNCHD, MANAGER_SYSTEMD_USER}
SYSTEMD_MARKER = "# Generated by goal-cli system heartbeat. Do not edit by hand."


@dataclass(frozen=True)
class ManagedFile:
    path: Path
    content: str


@dataclass(frozen=True)
class SystemHeartbeatLayout:
    manager: str
    label: str
    config_path: Path
    project_root: Path
    log_dir: Path
    interval_seconds: int
    max_minutes: float
    tick_args: tuple[str, ...]
    files: tuple[ManagedFile, ...]


@dataclass(frozen=True)
class SystemHeartbeatOptions:
    manager: str = MANAGER_AUTO
    label: str | None = None
    every_minutes: float = 60.0
    max_minutes: float = 30.0
    start: bool = True
    force: bool = False
    dry_run: bool = False


@dataclass(frozen=True)
class SystemHeartbeatResult:
    exit_code: int
    messages: tuple[str, ...] = ()
    errors: tuple[str, ...] = ()


def install_system_heartbeat(config: GoalConfig, options: SystemHeartbeatOptions) -> SystemHeartbeatResult:
    layout_or_error = _validated_layout(config, options)
    if isinstance(layout_or_error, SystemHeartbeatResult):
        return layout_or_error
    layout = layout_or_error

    config_issues = validate_config(config)
    if config_issues:
        return SystemHeartbeatResult(2, errors=tuple(config_issues))

    messages = [
        f"manager: {layout.manager}",
        f"label: {layout.label}",
        f"config: {layout.config_path}",
        f"project root: {layout.project_root}",
        f"logs: {layout.log_dir}",
        f"tick: {shlex.join(layout.tick_args)}",
    ]

    for managed_file in layout.files:
        if options.dry_run:
            messages.append(f"would write {managed_file.path}")
            continue
        try:
            action = _write_managed_file(managed_file, layout, force=options.force)
        except OSError as exc:
            return SystemHeartbeatResult(1, tuple(messages), (str(exc),))
        messages.append(action)

    if options.dry_run:
        for command in _activation_commands(layout):
            messages.append(f"would run: {shlex.join(command)}")
        return SystemHeartbeatResult(0, tuple(messages))

    if not options.start:
        messages.append("installed but not started")
        return SystemHeartbeatResult(0, tuple(messages))

    activation = _run_activation(layout)
    return SystemHeartbeatResult(
        activation.exit_code,
        tuple(messages + list(activation.messages)),
        activation.errors,
    )


def uninstall_system_heartbeat(config: GoalConfig, *, manager: str = MANAGER_AUTO, label: str | None = None, dry_run: bool = False) -> SystemHeartbeatResult:
    layout_or_error = _validated_layout(
        config,
        SystemHeartbeatOptions(manager=manager, label=label, dry_run=dry_run),
        validate_interval=False,
    )
    if isinstance(layout_or_error, SystemHeartbeatResult):
        return layout_or_error
    layout = layout_or_error

    messages = [f"manager: {layout.manager}", f"label: {layout.label}"]
    if dry_run:
        for command in _deactivation_commands(layout):
            messages.append(f"would run: {shlex.join(command)}")
        for managed_file in layout.files:
            messages.append(f"would remove {managed_file.path}")
        return SystemHeartbeatResult(0, tuple(messages))

    deactivation = _run_deactivation(layout)
    messages.extend(deactivation.messages)
    errors = list(deactivation.errors)

    for managed_file in layout.files:
        try:
            managed_file.path.unlink()
            messages.append(f"removed {managed_file.path}")
        except FileNotFoundError:
            messages.append(f"already absent {managed_file.path}")
        except OSError as exc:
            errors.append(str(exc))

    if layout.manager == MANAGER_SYSTEMD_USER and shutil.which("systemctl"):
        reload_result = _run_command(("systemctl", "--user", "daemon-reload"), allow_failure=True)
        messages.extend(reload_result.messages)
        errors.extend(reload_result.errors)

    return SystemHeartbeatResult(1 if errors else 0, tuple(messages), tuple(errors))


def status_system_heartbeat(config: GoalConfig, *, manager: str = MANAGER_AUTO, label: str | None = None) -> SystemHeartbeatResult:
    layout_or_error = _validated_layout(
        config,
        SystemHeartbeatOptions(manager=manager, label=label),
        validate_interval=False,
    )
    if isinstance(layout_or_error, SystemHeartbeatResult):
        return layout_or_error
    layout = layout_or_error

    messages = [
        f"manager: {layout.manager}",
        f"label: {layout.label}",
        f"config: {layout.config_path}",
        f"project root: {layout.project_root}",
        f"logs: {layout.log_dir}",
        "files:",
    ]
    for managed_file in layout.files:
        state = "present" if managed_file.path.exists() else "missing"
        messages.append(f"- {managed_file.path} ({state})")

    command = _status_command(layout)
    if command is None:
        return SystemHeartbeatResult(0, tuple(messages + ["status command unavailable for this manager"]))
    status = _run_command(command, allow_failure=True)
    return SystemHeartbeatResult(status.exit_code, tuple(messages + list(status.messages)), status.errors)


def paths_system_heartbeat(config: GoalConfig, *, manager: str = MANAGER_AUTO, label: str | None = None) -> SystemHeartbeatResult:
    layout_or_error = _validated_layout(
        config,
        SystemHeartbeatOptions(manager=manager, label=label),
        validate_interval=False,
    )
    if isinstance(layout_or_error, SystemHeartbeatResult):
        return layout_or_error
    layout = layout_or_error

    messages = [
        f"manager: {layout.manager}",
        f"label: {layout.label}",
        f"config: {layout.config_path}",
        f"project root: {layout.project_root}",
        f"logs: {layout.log_dir}",
        f"tick: {shlex.join(layout.tick_args)}",
        "files:",
    ]
    messages.extend(f"- {managed_file.path}" for managed_file in layout.files)
    return SystemHeartbeatResult(0, tuple(messages))


def run_system_heartbeat_tick(config: GoalConfig, *, max_minutes: float = 30.0) -> SystemHeartbeatResult:
    if max_minutes < 0:
        return SystemHeartbeatResult(2, errors=("--max-minutes must be non-negative",))

    cleanup = cleanup_runtime(config, kill_orphans=False)
    messages = list(cleanup.actions)
    errors = [f"warning: {warning}" for warning in cleanup.warnings]

    result = run_goal(config, RuntimeOptions(max_minutes=max_minutes))
    messages.append(result.message)
    if result.run_dir:
        messages.append(f"Run directory: {result.run_dir}")

    if result.status == "locked":
        messages.append("heartbeat tick skipped because another heartbeat is active")
        return SystemHeartbeatResult(0, tuple(messages), tuple(errors))
    return SystemHeartbeatResult(result.exit_code, tuple(messages), tuple(errors))


def build_system_heartbeat_layout(config: GoalConfig, options: SystemHeartbeatOptions) -> SystemHeartbeatLayout:
    manager = resolve_manager(options.manager)
    label = normalize_label(options.label or default_label(config))
    interval_seconds = minutes_to_seconds(options.every_minutes, "--every-minutes")
    if options.max_minutes < 0:
        raise ValueError("--max-minutes must be non-negative")

    config_path = config.path.resolve()
    project_root = config.root.resolve()
    log_dir = (config.state_dir / "system-heartbeat").resolve()
    tick_args = build_tick_args(config_path, options.max_minutes)
    base_layout = SystemHeartbeatLayout(
        manager=manager,
        label=label,
        config_path=config_path,
        project_root=project_root,
        log_dir=log_dir,
        interval_seconds=interval_seconds,
        max_minutes=options.max_minutes,
        tick_args=tick_args,
        files=(),
    )
    files: tuple[ManagedFile, ...]
    if manager == MANAGER_LAUNCHD:
        files = (ManagedFile(_launchd_path(label), render_launchd_plist(base_layout)),)
    else:
        service_path, timer_path = _systemd_paths(label)
        files = (
            ManagedFile(service_path, render_systemd_service(base_layout)),
            ManagedFile(timer_path, render_systemd_timer(base_layout)),
        )
    return SystemHeartbeatLayout(
        manager=base_layout.manager,
        label=base_layout.label,
        config_path=base_layout.config_path,
        project_root=base_layout.project_root,
        log_dir=base_layout.log_dir,
        interval_seconds=base_layout.interval_seconds,
        max_minutes=base_layout.max_minutes,
        tick_args=base_layout.tick_args,
        files=files,
    )


def build_tick_args(config_path: Path, max_minutes: float) -> tuple[str, ...]:
    return (
        str(Path(sys.executable).resolve()),
        "-m",
        "goal_cli.cli",
        "-c",
        str(config_path.resolve()),
        "heartbeat",
        "tick",
        "--max-minutes",
        _format_minutes(max_minutes),
    )


def render_launchd_plist(layout: SystemHeartbeatLayout) -> str:
    plist = {
        "Label": layout.label,
        "ProgramArguments": list(layout.tick_args),
        "WorkingDirectory": str(layout.project_root),
        "StartInterval": layout.interval_seconds,
        "RunAtLoad": True,
        "StandardOutPath": str(layout.log_dir / "launchd.out.log"),
        "StandardErrorPath": str(layout.log_dir / "launchd.err.log"),
    }
    return plistlib.dumps(plist, sort_keys=False).decode("utf-8")


def render_systemd_service(layout: SystemHeartbeatLayout) -> str:
    return "\n".join(
        [
            SYSTEMD_MARKER,
            "[Unit]",
            f"Description=goal-cli heartbeat for {layout.label}",
            "After=network-online.target",
            "",
            "[Service]",
            "Type=oneshot",
            f"WorkingDirectory={_systemd_value(str(layout.project_root))}",
            f"ExecStart={shlex.join(layout.tick_args)}",
            "Environment=PYTHONUNBUFFERED=1",
            f"StandardOutput=append:{_systemd_value(str(layout.log_dir / 'systemd.out.log'))}",
            f"StandardError=append:{_systemd_value(str(layout.log_dir / 'systemd.err.log'))}",
            "",
        ]
    )


def render_systemd_timer(layout: SystemHeartbeatLayout) -> str:
    return "\n".join(
        [
            SYSTEMD_MARKER,
            "[Unit]",
            f"Description=Run {layout.label} on a timer",
            "",
            "[Timer]",
            "OnBootSec=1min",
            f"OnUnitActiveSec={layout.interval_seconds}s",
            "AccuracySec=1min",
            "Persistent=true",
            f"Unit={layout.label}.service",
            "",
            "[Install]",
            "WantedBy=timers.target",
            "",
        ]
    )


def resolve_manager(manager: str) -> str:
    if manager not in SUPPORTED_MANAGERS:
        raise ValueError(f"--manager must be one of: {', '.join(sorted(SUPPORTED_MANAGERS))}")
    if manager != MANAGER_AUTO:
        return manager
    if sys.platform == "darwin":
        return MANAGER_LAUNCHD
    if sys.platform.startswith("linux"):
        return MANAGER_SYSTEMD_USER
    raise ValueError("auto manager only supports macOS launchd and Linux systemd user timers")


def default_label(config: GoalConfig) -> str:
    name = re.sub(r"[^A-Za-z0-9_.-]+", "-", config.name).strip("-._") or "goal"
    digest = hashlib.sha1(str(config.root.resolve()).encode("utf-8")).hexdigest()[:10]
    return f"com.goal-cli.{name}.{digest}"


def normalize_label(label: str) -> str:
    if not label or not label.strip():
        raise ValueError("--label must not be empty")
    normalized = label.strip()
    if "/" in normalized or "\\" in normalized:
        raise ValueError("--label must not contain path separators")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", normalized):
        raise ValueError("--label may contain only letters, digits, dot, underscore, and hyphen")
    return normalized


def minutes_to_seconds(minutes: float, flag: str) -> int:
    if minutes <= 0:
        raise ValueError(f"{flag} must be positive")
    seconds = int(round(minutes * 60))
    if seconds < 1:
        raise ValueError(f"{flag} must be at least one second")
    return seconds


def _validated_layout(
    config: GoalConfig,
    options: SystemHeartbeatOptions,
    *,
    validate_interval: bool = True,
) -> SystemHeartbeatLayout | SystemHeartbeatResult:
    try:
        layout_options = options
        if not validate_interval:
            layout_options = SystemHeartbeatOptions(
                manager=options.manager,
                label=options.label,
                every_minutes=60.0,
                max_minutes=max(0.0, options.max_minutes),
                start=options.start,
                force=options.force,
                dry_run=options.dry_run,
            )
        return build_system_heartbeat_layout(config, layout_options)
    except ValueError as exc:
        return SystemHeartbeatResult(2, errors=(str(exc),))


def _launchd_path(label: str) -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"


def _systemd_paths(label: str) -> tuple[Path, Path]:
    config_home = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")).expanduser()
    unit_dir = config_home / "systemd" / "user"
    return unit_dir / f"{label}.service", unit_dir / f"{label}.timer"


def _write_managed_file(managed_file: ManagedFile, layout: SystemHeartbeatLayout, *, force: bool = False) -> str:
    path = managed_file.path
    content = managed_file.content
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except UnicodeDecodeError as exc:
            raise OSError(f"refusing to overwrite unreadable service file: {path}") from exc
        if existing == content:
            return f"unchanged {path}"
        if not force and not _looks_goal_cli_managed(path, existing, layout):
            raise OSError(f"refusing to overwrite unmanaged service file: {path}")

    path.parent.mkdir(parents=True, exist_ok=True)
    layout.log_dir.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    temp_path.write_text(content, encoding="utf-8")
    temp_path.replace(path)
    return f"wrote {path}"


def _looks_goal_cli_managed(path: Path, existing: str, layout: SystemHeartbeatLayout) -> bool:
    if path.suffix in {".service", ".timer"}:
        return SYSTEMD_MARKER in existing
    if path.suffix == ".plist":
        try:
            parsed = plistlib.loads(existing.encode("utf-8"))
        except Exception:
            return False
        if parsed.get("Label") != layout.label:
            return False
        args = parsed.get("ProgramArguments", [])
        return isinstance(args, list) and "goal_cli.cli" in args and "heartbeat" in args
    return False


def _activation_commands(layout: SystemHeartbeatLayout) -> tuple[tuple[str, ...], ...]:
    if layout.manager == MANAGER_LAUNCHD:
        return (
            ("launchctl", "bootout", f"gui/{os.getuid()}", str(layout.files[0].path)),
            ("launchctl", "bootstrap", f"gui/{os.getuid()}", str(layout.files[0].path)),
            ("launchctl", "kickstart", "-k", f"gui/{os.getuid()}/{layout.label}"),
        )
    return (
        ("systemctl", "--user", "daemon-reload"),
        ("systemctl", "--user", "enable", "--now", f"{layout.label}.timer"),
    )


def _deactivation_commands(layout: SystemHeartbeatLayout) -> tuple[tuple[str, ...], ...]:
    if layout.manager == MANAGER_LAUNCHD:
        return (("launchctl", "bootout", f"gui/{os.getuid()}", str(layout.files[0].path)),)
    return (
        ("systemctl", "--user", "disable", "--now", f"{layout.label}.timer"),
        ("systemctl", "--user", "daemon-reload"),
    )


def _status_command(layout: SystemHeartbeatLayout) -> tuple[str, ...] | None:
    if layout.manager == MANAGER_LAUNCHD:
        return ("launchctl", "print", f"gui/{os.getuid()}/{layout.label}")
    if layout.manager == MANAGER_SYSTEMD_USER:
        return ("systemctl", "--user", "status", f"{layout.label}.timer", "--no-pager")
    return None


def _run_activation(layout: SystemHeartbeatLayout) -> SystemHeartbeatResult:
    if layout.manager == MANAGER_LAUNCHD:
        if not shutil.which("launchctl"):
            return SystemHeartbeatResult(1, errors=("launchctl not found on PATH",))
        messages: list[str] = []
        errors: list[str] = []
        for index, command in enumerate(_activation_commands(layout)):
            result = _run_command(command, allow_failure=index == 0)
            messages.extend(result.messages)
            errors.extend(result.errors)
            if result.exit_code and index != 0:
                return SystemHeartbeatResult(result.exit_code, tuple(messages), tuple(errors))
        return SystemHeartbeatResult(0, tuple(messages), tuple(errors))

    if not shutil.which("systemctl"):
        return SystemHeartbeatResult(1, errors=("systemctl not found on PATH",))
    return _run_commands(_activation_commands(layout))


def _run_deactivation(layout: SystemHeartbeatLayout) -> SystemHeartbeatResult:
    if layout.manager == MANAGER_LAUNCHD and not shutil.which("launchctl"):
        return SystemHeartbeatResult(0, messages=("launchctl not found; removed files only",))
    if layout.manager == MANAGER_SYSTEMD_USER and not shutil.which("systemctl"):
        return SystemHeartbeatResult(0, messages=("systemctl not found; removed files only",))
    return _run_commands(_deactivation_commands(layout), allow_failure=True)


def _run_commands(commands: tuple[tuple[str, ...], ...], *, allow_failure: bool = False) -> SystemHeartbeatResult:
    messages: list[str] = []
    errors: list[str] = []
    for command in commands:
        result = _run_command(command, allow_failure=allow_failure)
        messages.extend(result.messages)
        errors.extend(result.errors)
        if result.exit_code and not allow_failure:
            return SystemHeartbeatResult(result.exit_code, tuple(messages), tuple(errors))
    return SystemHeartbeatResult(1 if errors and not allow_failure else 0, tuple(messages), tuple(errors))


def _run_command(command: tuple[str, ...], *, allow_failure: bool = False) -> SystemHeartbeatResult:
    try:
        completed = subprocess.run(command, capture_output=True, text=True, timeout=30)
    except FileNotFoundError:
        return SystemHeartbeatResult(1, errors=(f"command not found: {command[0]}",))
    except subprocess.TimeoutExpired:
        return SystemHeartbeatResult(1, errors=(f"command timed out: {shlex.join(command)}",))

    messages = [f"ran: {shlex.join(command)}"]
    if completed.stdout.strip():
        messages.append(completed.stdout.strip())
    stderr = completed.stderr.strip()
    if stderr and allow_failure:
        messages.append(stderr)
    errors = (stderr,) if stderr and not allow_failure else ()
    if completed.returncode and not allow_failure:
        return SystemHeartbeatResult(completed.returncode, tuple(messages), errors)
    return SystemHeartbeatResult(0 if allow_failure else completed.returncode, tuple(messages), errors)


def _format_minutes(minutes: float) -> str:
    if float(minutes).is_integer():
        return str(int(minutes))
    return str(minutes)


def _systemd_value(value: str) -> str:
    return value.replace("%", "%%")
